services:
  remotion-app:
    build:
      context: .
      dockerfile: ./remotion/Dockerfile
    depends_on:
      - backend
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile